application:
  name: simple-example-with-postgresql
  project: simple-example-with-postgresql-project
  cloud_region: aws/eu-west-3
  publicly_accessible: true
databases:
- type: postgresql
  version: "11.5"
  name: my-postgresql-3498225
routers:
- name: main
  routes:
  - application_name: simple-example-with-postgresql
    paths:
    - /*
