server:
  port: 8080

spring:
  jackson:
    property-naming-strategy: "CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES"
    date-format: "yyyy-MM-dd'T'HH:mm:ss'Z'"
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_empty
  jpa:
    hibernate:
      # Don't do this at home...
      ddl-auto: update
